/**
 * Pathfinder 2e Game Pack
 *
 * Self-contained system pack that plugs into the Combat Engine v2
 * and the PathfinderCharacterCreator page, mirroring the structure of
 * src/game-packs/dnd5e/.
 *
 * Data + content modules are auto-generated by
 * scripts/build-pf2e-pack.mjs from the pruned Foundry source dump at
 * src/game-packs/pf2e/pf2e-foundry-source/. Re-run that script after
 * updating the source and commit the generated diff alongside.
 *
 * Lazy-loaded: each pack is exposed as a dynamic-import getter so the
 * main creator chunk doesn't pay the 18 MB content cost up front.
 * Callers `await getAncestries()` etc. and the per-pack module loads
 * on demand. Vite code-splits each one into its own chunk.
 *
 * License: hybrid — Apache 2.0 (code) + ORC (Remaster content) +
 * OGL 1.0a (legacy items) + Paizo CUP (trademarks). Full attribution
 * at LICENSES/PATHFINDER_2E.md.
 */

// --- Picker-essential content (lazy) -----------------------------------------
export const getAncestries  = () => import("./content/ancestries.js").then((m) => m.ancestries);
export const getHeritages   = () => import("./content/heritages.js").then((m) => m.heritages);
export const getBackgrounds = () => import("./content/backgrounds.js").then((m) => m.backgrounds);
export const getClasses     = () => import("./content/classes.js").then((m) => m.classes);
export const getDeities     = () => import("./content/deities.js").then((m) => m.deities);
export const getFeats       = () => import("./content/feats.js").then((m) => m.feats);
export const getSpells      = () => import("./content/spells.js").then((m) => m.spells);
export const getEquipment   = () => import("./content/equipment.js").then((m) => m.equipment);

// --- Mechanic data (lazy) ---------------------------------------------------
export const getConditions          = () => import("./data/conditions.js").then((m) => m.conditions);
export const getClassFeatures       = () => import("./data/classFeatures.js").then((m) => m.classFeatures);
export const getAncestryFeatures    = () => import("./data/ancestryFeatures.js").then((m) => m.ancestryFeatures);
export const getFamiliarAbilities   = () => import("./data/familiarAbilities.js").then((m) => m.familiarAbilities);
export const getActions             = () => import("./data/actions.js").then((m) => m.actions);
export const getFeatEffects         = () => import("./data/featEffects.js").then((m) => m.featEffects);
export const getSpellEffects        = () => import("./data/spellEffects.js").then((m) => m.spellEffects);
export const getEquipmentEffects    = () => import("./data/equipmentEffects.js").then((m) => m.equipmentEffects);
export const getOtherEffects        = () => import("./data/otherEffects.js").then((m) => m.otherEffects);

// --- Pack metadata -----------------------------------------------------------
// Wired for the PathfinderCharacterCreator route (src/pages/
// PathfinderCharacterCreator.jsx) — already merged via main. The step
// components under src/game-packs/pf2e/ui/steps/ are scaffolded but
// haven't been hooked up to read from these accessors yet — that's
// the next commit on the PF2e stack.

export const PACK_META = {
  id: "pathfinder_2e",
  name: "Pathfinder (2nd Edition)",
  edition: "remaster",
  ready: true,
  source: {
    repo: "https://github.com/foundryvtt/pf2e",
    // SHA / tag filled in by `node scripts/inscribe-pf2e-source-version.mjs`
    // — for now placeholders that match the LICENSES/PATHFINDER_2E.md
    // "Source provenance" table values.
    commit: null,
    tag: null,
  },
  licenses: ["Apache-2.0", "ORC", "OGL-1.0a", "Paizo-CUP"],
};

// Re-exported for the Combat Engine v2 game-pack contract that the
// dnd5e pack uses. Keeping the shape so PF2e plugs into the same
// dispatcher without special-case branches.
export const pf2eGamePack = {
  id: "pathfinder_2e",
  name: "Pathfinder (2nd Edition)",
  ready: true,

  // Lazy accessors — content lives in per-pack modules to keep the
  // main bundle slim.
  content: {
    ancestries:  getAncestries,
    heritages:   getHeritages,
    backgrounds: getBackgrounds,
    classes:     getClasses,
    deities:     getDeities,
    feats:       getFeats,
    spells:      getSpells,
    equipment:   getEquipment,
  },

  data: {
    conditions:        getConditions,
    classFeatures:     getClassFeatures,
    ancestryFeatures:  getAncestryFeatures,
    familiarAbilities: getFamiliarAbilities,
    actions:           getActions,
    featEffects:       getFeatEffects,
    spellEffects:      getSpellEffects,
    equipmentEffects:  getEquipmentEffects,
    otherEffects:      getOtherEffects,
  },

  // Rule resolvers stay null until the PF2e mechanic helpers ship.
  // Combat Engine v2 dispatcher falls back to a "no-op resolver"
  // when these are absent — the creator works without them; only
  // combat/sheet rendering needs them.
  rules: {
    resolveAction: null,
    armorClass:    null,
  },
};

export default pf2eGamePack;
