// Per-subclass new-player tips.
//
// Two-level dictionary: class slug → subclass id → tip string.
//
// Subclass IDs follow the picker's `class-details.json` short IDs where a
// picker exists (Barbarian, Rogue today). For classes whose picker has
// not been wired yet (Champion, Ranger, Swashbuckler in this batch), the
// IDs match the canonical Foundry class-feature slugs from
// audits/pf2e_subclass_inventory.json — the tips sit dormant until a
// picker for that class is added, at which point the IDs line up.
//
// Tip strings may contain inline [[slug]] markers parsed by AnnotatedText
// against the foundational glossary.

export const SUBCLASS_TIPS = {
  // ─── BARBARIAN INSTINCTS ────────────────────────────────────────────────
  barbarian: {
    animal: "Channel a wild predator. Pick an animal (ape, bear, deer, frog, shark, snake, spider, wolf) — your Rage replaces your weapon attacks with that animal's unarmed strike. Bears get claws, snakes get fangs and a constrict, spiders get web — each animal grants different mechanical options and a thematic feel. While raging you can't use weapons; the animal IS your weapon. Pairs well with [[ancestry-feat|ancestry feats]] that lean into natural attacks. Anathema is disrespecting your chosen animal — flavor with mechanical teeth. Best for players who want a transformation fantasy in combat. Skip if you prefer wielding a specific weapon throughout.",
    dragon: "Channel draconic ancestry. Pick a dragon type — your Rage damage shifts to that dragon's elemental damage type (fire for red, cold for white, electricity for blue, etc.). At higher levels you can spend a [[focus-pool|focus]] action for a breath-weapon-like cone or line attack. Anathema is allowing disrespect to your dragon type. Pairs well with characters built around a specific elemental theme. Best for players who want martial damage with elemental flavor and the occasional area-of-effect option. Skip if you want pure physical damage without elemental complications — Dragon's damage-type shift can hurt you against resistant enemies.",
    elemental: "Bond with one of the elemental planes (air, earth, fire, metal, water, wood). Your Rage damage takes on that element's damage type, and you gain elemental resistances at higher levels. Similar to Dragon Instinct mechanically but tied to elemental planes and creatures rather than dragons. Anathema is disrespecting your chosen element's elementals. Best for players who want elemental flavor without committing to a specific dragon mythology. Skip if you want martial damage that always lands — elemental damage types can be resisted.",
    fury: "Pure unfiltered rage with no source mythology — your fury wells from your own heart. NO anathema, NO instinct ability — you trade those for an EXTRA [[class-feat|class feat]] at level 1 AND increased Rage damage (jumps from 2 to 6, escalating to 12 at higher levels). The simplest instinct mechanically; the most damaging numerically. Pairs with literally any campaign — no flavor restrictions, no anathema to watch. Best for players who want straightforward 'big damage, simple rules' Barbarian play. Skip only if you want the flavor of a specific instinct's theme.",
    giant: "Channel the raw power and size of giants. The signature feature: you can wield weapons sized for a [[size|Large]] creature even if you're Small or Medium, dealing massive damage at the cost of clumsiness (–2 to attack rolls while using oversized weapons during Rage). Anathema is letting an insult to giants slide. The trade-off is brutal: harder to hit, but the damage when you DO hit is staggering. Pairs with reach weapons and high-crit builds. Best for players who want maximum damage swings — the 'either crit or whiff' style. Skip if you want consistent hits — Giant's penalty is a real cost.",
    spirit: "Channel ancestral or spectral powers. Your Rage damage shifts to negative or void damage — perfect against undead and living creatures alike (though some undead resist negative). Higher levels grant access to spirit-themed [[focus-spell|focus spells]] and resistances to negative effects. Anathema is disrespecting corpses or spirits. Best for undead-heavy campaigns or for players who want martial flavor with a haunted backstory. Skip if your party already has anti-undead specialists — Spirit Instinct's edge case is exactly what other classes already cover.",
    superstition: "Anti-magic Barbarian. While raging you gain +2 to [[saving-throw|saves]] against magic AND deal extra Rage damage to anyone you've witnessed casting a [[spell]] recently. The anathema is steep: you cannot learn or cast spells, or use spell-activated items — accepting magic willingly even from allies makes you Frightened. Best for campaigns with caster-heavy enemies and parties that don't rely on you for magical buff acceptance. Skip if your party uses heal-via-magic frequently — Superstition's anti-magic stance creates real friction with party cleric/druid support.",
    bloodrager: "The blood-drinker. Drinking the potent magical blood of supernatural creatures has changed you — awakened arcane or divine power, and a grim thirst that won't go quiet. Source: War of Immortals. Your Blood Rage instinct ability makes your physical [[strike|Strikes]] deal extra persistent bleed damage equal to half your Rage bonus. When you cast a [[spell]] that requires a [[spell-attack|spell attack]] roll while raging, your Rage damage applies to that spell — even on a miss. Raging Resistance grants slashing resistance AND persistent bleed resistance AND resistance to damage from the last creature whose blood you drank.\n\nPaired with the Bloodrager class archetype: gain a [[charisma|CHA]]-based [[spontaneous-casting|spell repertoire]] (arcane or divine tradition) with [[cantrip|cantrips]] and spells fueled by Harvest Blood — a special [[action]] that lets you consume blood from a successful piercing or slashing Strike, reducing your drained condition.\n\nPlays as the vampiric-feeling combat caster — magic AS appetite, blood AS resource. Pairs with builds that lean into bleed damage and the drained-condition trade-off. Best for players who want the 'blood mage who rages' fantasy — visceral, hungry, dangerous. Skip if you don't want curse-style resource management — Bloodrager's drained mechanic is a constant tax.",
  },

  // ─── CHAMPION CAUSES (picker not yet wired — IDs match Foundry slugs) ───
  champion: {
    justice: "The shining knight. Tenets of Good: never act against innocents, defend the helpless, respect lawful authority unless it conflicts with deeper good. Your reactive ability is Retributive Strike — when an ally near you is hit, you deal damage to the attacker. Excellent for protecting squishy allies; the threat of your reaction makes enemies think twice about ignoring you. Pairs well with parties that have casters or archers behind you. Best for players who want the classic 'shining defender' fantasy. Skip if you want moral flexibility — Justice's tenets are strict and consistent.",
    liberation: "The defender of freedom. Tenets of Good combined with anti-tyranny — you must aid those whose freedom is threatened, can't enslave or oppress. Your reactive ability is Liberating Step — when an ally near you is grabbed, restrained, or otherwise restricted, you can free them as a [[reaction]]. Excellent against monsters with grapples, charms, or holds. Pairs with parties facing enchanter or beholder-style opposition. Best for players who want anti-tyranny themes and a less rigid version of the holy knight fantasy. Skip if your party doesn't typically face grappling/binding opposition — the reaction's specific trigger is real.",
    redemption: "The merciful warrior. Tenets of Good plus an obligation to offer enemies a chance to relent before killing them. Your reactive ability is Glimpse of Redemption — when an ally is hit, the attacker chooses: stop attacking the ally (and become enfeebled briefly) or take resistance-reduced damage themselves. Excellent at de-escalating fights and protecting allies through choice manipulation. Pairs with parties that benefit from narrative-driven combat over kill-everything tactics. Best for players who want the 'show mercy where possible' fantasy. Skip if your campaign features purely evil enemies who'll never accept mercy — Redemption's option becomes redundant.",
    iniquity: "The fallen knight. Tenets of Evil mirror of Justice — you embrace cruelty, manipulate the weak, scorn mercy. Your reactive ability flavors as vengeful spite — when allies are wronged, the offender suffers. Anathema is allowing kindness to define your behavior. Pairs with morally complex campaigns or evil-aligned parties (rare but possible). Best for players who want the dark mirror of the holy knight fantasy. Skip if your campaign or table doesn't support evil-aligned PCs — Iniquity is fundamentally a villainous archetype.",
    obedience: "The dominating ruler. Tenets of Evil plus an obsession with control — you must impose order through fear, dominate the weak, deny freedom to those beneath you. Your reactive ability is Destructive Vengeance — when allies are crossed, the offender takes additional damage as punishment. Anathema is allowing disobedience to go unpunished. Best for villain campaigns or 'controlled chaos' party dynamics. Skip if your party isn't evil — Obedience's control theme grates against good-aligned dynamics.",
    desecration: "The corruptor. Tenets of Evil plus a drive to defile sacred things — holy ground, holy creatures, sacred objects. Your reactive ability lets you defile a hostile aura around you, draining ally power. Anathema is showing reverence for things others find holy. Best for evil campaigns where corruption is the goal. Skip if your party is good-aligned — Desecration's identity centers on actively undermining good-aligned allies' values.",
    grandeur: "Tenets that honor martial glory and inspiring presence. Your reactive ability emphasizes commanding the battlefield through display — bolstering allies' morale, demanding attention from enemies, or making your own deeds rally those around you. The 'shining hero' cause in the literal inspiration sense — your every act on the field is meant to be seen and remembered. Pairs well with [[charisma|CHA]]-heavy builds and parties that benefit from inspirational leadership. Best for players who want the 'main character energy' Champion — the one whose presence raises everyone's game. Skip if you prefer the quieter defender style — Grandeur is loud by design.",
  },

  // ─── RANGER HUNTER'S EDGES (picker not yet wired) ──────────────────────
  ranger: {
    flurry: "Multi-attack specialist. Your Hunt Prey grants reduced [[multiple-attack-penalty|MAP]] against your designated target — −3/−6 instead of the standard −5/−10. The math turns triple-Striking from 'usually a bad idea' to 'genuinely viable'. Pairs with two-weapon fighting, agile weapons, and any build that wants to swing multiple times per turn against the same enemy. Best for players who want to maximize attack volume — bows, dual blades, or grappler builds. Skip if you prefer single big strikes — Precision is the alternative for that style.",
    outwit: "Tactical and informational specialist. Your Hunt Prey grants [[skill]] bonuses to [[deception|Deception]], [[intimidation|Intimidation]], [[stealth|Stealth]], and Recall Knowledge checks against the target, plus a bonus to [[armor-class|AC]] specifically against the target's attacks. Less direct damage than Flurry or Precision; more about tactical advantage and survivability. Best for players who want their Ranger to be the party's tracker-and-tactician. Pairs well with [[intelligence|INT]]-heavy builds and skill-focused playstyles. Skip if you want pure combat optimization — Outwit's bonuses are diffuse rather than concentrated.",
    precision: "Big-hit specialist. Your first hit against your Hunted Prey each round deals significant bonus damage — 1d8 at low levels, scaling up. The damage is added to a single hit, making each round feature one impactful strike. Pairs perfectly with high-crit builds and weapons with strong base damage (bows, crossbows, heavy melee). Best for players who want the 'ranger as sniper' or 'ranger as duelist' fantasy. Skip if you want to attack multiple times per round consistently — Flurry handles that better.",
    vindicator: "The divine inquisitor. Use guile and magic to reveal hidden threats — monsters that lurk in the night or, worse, supernatural predators hiding among the faithful. Source: War of Immortals.\n\nYour Vindication Hunter's Edge grants a +1 status bonus to [[spell-attack|spell attack]] rolls against your hunted prey, and prey takes a –1 status penalty to [[saving-throw|saves]] against your [[divine]] spells. You learn the Vindicator's Mark warden spell — launch a magical dart that marks your prey with a glowing nimbus only you can see, adding +2 damage from your weapon attacks. Dismiss it on a damaging hit for a 2d6 spirit damage burst.\n\nPaired with the Vindicator class archetype: choose a deity and gain sanctification, train in [[religion|Religion]] instead of [[nature|Nature]], get your deity's favored weapon, and your warden spells become divine ([[wisdom|WIS]]-based) instead of [[primal]].\n\nPlays as the magical bounty hunter — a religious inquisitor more than a wilderness scout. Pairs with builds that lean into divine flavor and parties dealing with undead, fiends, or infiltrators. Best for players who want the 'witch-hunter / inquisitor' fantasy. Skip if you want secular Ranger play — Vindicator demands religious affiliation and reshapes your spellcasting around it.",
  },

  // ─── ROGUE RACKETS ──────────────────────────────────────────────────────
  rogue: {
    'eldritch-trickster': "The magic-using sneak. Key ability options include [[charisma|CHA]] or another spellcasting stat alongside [[dexterity|DEX]]. Your racket grants access to a small selection of [[spell|spells]] from one tradition, scaling up as you level. Effectively makes you a magic-dabbling Rogue without going full multiclass. Best for players who want the 'arcane assassin' or 'shadow magic thief' fantasy — magical utility on top of Rogue's signature [[skill]] mastery. Skip if you don't want spell management on top of Rogue's positioning game — Eldritch Trickster adds real complexity.",
    mastermind: "The brain-over-brawn rogue. Key ability is [[intelligence|INT]] — your Sneak Attack triggers off making Recall Knowledge against an enemy AND succeeding, not off positioning alone. Trades the flanking-and-feinting playstyle for a tactical 'study before strike' approach. Pairs well with [[society|Society]], [[arcana|Arcana]], and other knowledge skills. Best for players who want a cerebral Rogue — Sherlock Holmes meets dagger work. Skip if you want straightforward Sneak Attack triggers — Mastermind's setup involves more reading the room than positioning.",
    ruffian: "The brawler thief. Key ability is [[strength|STR]] — your racket grants Sneak Attack with medium armor and martial weapons (instead of the typical light armor + finesse weapons). Heavier hits, more durability, but reduced [[stealth|Stealth]] effectiveness due to armor noise. Pairs well with mauls, picks, and heavy weapons. Best for players who want the 'street thug' fantasy — Rogues who don't sneak in shadows but punch their way into ambushes. Skip if you want delicate finesse weapon play — Ruffian leans STR-loud.",
    scoundrel: "The trickster face. Key ability is [[charisma|CHA]] — Sneak Attack triggers off successful Feint actions, which use [[deception|Deception]] to make enemies flat-footed against you. Plays as a fast-talking street trickster who weaponizes social interaction even mid-combat. Pairs with high-CHA builds and any party that needs a social face. Best for players who want their Rogue to be the party diplomat-by-day, ambusher-by-night. Skip if you don't want to engage with social mechanics constantly — Scoundrel's identity is built around them.",
    thief: "The classic finesse thief. Key ability is [[dexterity|DEX]] — your racket lets you add DEX modifier to damage rolls with finesse weapons (normally STR adds to damage even on finesse weapons). DEX-based damage means you can build a fully agile Rogue without splitting stats. The default and most-played Rogue racket. Best for players who want the iconic 'small fast knife-user' fantasy — Rogue as nimble striker. Skip if you have a strong concept that points elsewhere; Thief is the safe default but other rackets offer more specific identity.",
    avenger: "The church's quiet blade. Trained far from watching eyes in remote monasteries or secret cloisters, indoctrinated in your deity's teachings while learning a variety of martial skills — often focused on the deity's favored weapon. Source: War of Immortals. Sometimes called 'slayers' under more brutal doctrines.\n\nYour racket uses [[stealth|stealth]], [[intimidation|Intimidation]], and deadly bladework to root out threats to the faith — heretics within the church, fiends among congregations, blasphemers who think themselves safe. Training often enforces vows of silence, celibacy, or other practices designed to keep avengers-in-training from forming strong personal attachments. The faith comes first; you come a distant second.\n\nMechanically you Sneak Attack church-defined targets and gain [[weapon-proficiency|proficiency]] with your deity's favored weapon. Sanctified to your deity (good, evil, or neutral depending on alignment).\n\nPlays as the dark mirror to the Champion — same divine devotion, opposite approach. Where Champions fight in the open, Avengers strike from shadow. Pairs with religious campaign themes and morally complex parties. Best for players who want the 'holy assassin' or 'inquisitor's blade' fantasy — devotion expressed as quiet violence. Skip if you don't want religious roleplay constraints — Avenger's identity is built around the church's needs above personal desires.",
  },

  // ─── SWASHBUCKLER STYLES (picker not yet wired) ────────────────────────
  swashbuckler: {
    battledancer: "Performance-fueled panache. You gain Panache through [[performance|Performance]] checks during combat — Tumble Through, Demoralize via display, or specific style actions. Trained in Performance automatically. Best for players who want the 'flashy showman' fantasy — combat as art form. Pairs with [[charisma|CHA]] builds where Performance is your social and combat skill simultaneously. Skip if you want a tactical, less theatrical Swashbuckler.",
    braggart: "Intimidation-fueled panache. You gain Panache through successful [[intimidation|Intimidation]] checks — primarily Demoralize. Trained in Intimidation automatically. Combat becomes a back-and-forth of taunts and threats backed by steel. Pairs well with high-CHA frontline builds. Best for players who want the 'cocky duelist' fantasy — talk loud, hit hard. Skip if Intimidation doesn't fit your character — Braggart leans into being a confident jerk in combat.",
    fencer: "Acrobatic panache. You gain Panache through successful [[acrobatics|Acrobatics]] Tumble Through actions — slip past enemies, gain Panache, then strike. Trained in Acrobatics automatically. The most physically dynamic style, emphasizing movement and positioning. Pairs with high-DEX builds and reach-conscious play. Best for players who want the 'duelist as dancer' fantasy — combat through grace. Skip if you don't want to constantly move around the battlefield — Fencer's style demands movement.",
    gymnast: "Athletics-fueled panache. You gain Panache through successful [[athletics|Athletics]] actions during combat — Grapple, Shove, Trip, Disarm. Trained in Athletics automatically. Combines Swashbuckler flair with grappler-style control mechanics. Pairs with [[strength|STR]] and [[dexterity|DEX]] dual focus. Best for players who want 'duelist meets wrestler' — flashy combat moves backed by physical control. Skip if you want to stay at weapon range — Gymnast pushes you into close-quarters combat.",
    wit: "Diplomacy-fueled panache. You gain Panache through successful [[diplomacy|Diplomacy]] actions during combat — primarily the Bon Mot skill feat (which acts as a verbal Demoralize). Trained in Diplomacy automatically. The most social style, emphasizing words over actions. Pairs with [[charisma|CHA]] builds where Diplomacy serves both social and combat needs. Best for players who want the 'duelist as silver-tongued charmer' fantasy. Skip if you don't want to engage in verbal jousting during fights — Wit's actions are talky by design.",
    rascal: "Deception-fueled panache. You gain Panache through successful [[deception|Deception]] Feints in combat. Trained in Deception automatically. The deceiver-duelist who confuses enemies into vulnerable positions. Pairs with builds that want to weave illusion and trickery into melee. Best for players who want the 'rogue meets swashbuckler' fantasy — deception applied with style. Skip if you want straightforward combat — Rascal's style requires setup feints every round.",
  },

  // ─── CLERIC DOCTRINES ──────────────────────────────────────────────────
  cleric: {
    cloistered: "The dedicated divine spellcaster. Light armor only — you trade combat presence for [[spell]]casting proficiency that ramps faster than any other doctrine. Reaches [[expert|Expert]] spellcasting at level 7, [[master|Master]] at level 15, [[legendary|Legendary]] at level 19. Auto-trained in your deity's [[divine]] skills. Domain Initiate at level 1 grants a [[focus-spell|focus spell]] tied to your deity's domains. Pairs with parties that have strong frontline coverage — you stay back and shape battles via spells. Best for players who want the iconic 'devout caster' fantasy — divine magic as your primary contribution. Skip if you want to fight in the front line — Cloistered's lower armor proficiency makes that risky.",
    warpriest: "The martial cleric. Medium armor [[proficiency]], trained in martial weapons, and access to a deity-favored weapon as a weapon group specialization. Slower spellcasting progression than Cloistered — reaches [[expert|Expert]] at level 9, [[master|Master]] at level 17, never reaches [[legendary|Legendary]]. The trade: you can hold the front line while still casting meaningful spells, but your top-tier magic always lags behind a dedicated caster. Pairs with parties needing a hybrid frontliner — half-tank, half-support. Best for players who want the 'crusader' fantasy — divine warrior who casts AND swings. Skip if you want pure casting or pure combat — Warpriest is deliberately the middle path.",
  },

  // ─── DRUID ORDERS ──────────────────────────────────────────────────────
  // Picker has 4 entries today (animal/leaf/storm/untamed-order); flame/
  // stone/wave-order tips sit dormant until Secrets of Magic orders are
  // added to the picker.
  druid: {
    'animal-order': "Bond with an animal companion. Your Order grants an Animal Companion at level 1 — a sturdy partner that scales with you across the campaign. Trained in [[athletics|Athletics]]. Order Spell is Heal Animal (focused healing for your companion). Anathema is cruelty to or unnecessary killing of animals. The most companion-focused Druid order — your strongest combat presence is often via your animal. Pairs with parties needing an extra frontline body. Best for players who want a constant animal partner — bear, wolf, eagle, etc. as a true second character. Skip if you don't want companion management — Animal Order is largely about commanding the companion in tandem with your own actions.",
    'leaf-order': "The plant-tender. Your Order grants a leshy [[ancestry-feat|familiar]] — a small plant-spirit companion. Trained in [[diplomacy|Diplomacy]]. Order Spell is a healing or growth-themed [[focus-spell|focus spell]]. Anathema is environmental destruction or cruelty to plants. Pairs with healing/support roles and parties that benefit from area-control via terrain shaping. Best for players who want the 'gardener-druid' fantasy — nature-as-nurture rather than nature-as-fury. Skip if you want combat-forward Druid play — Leaf Order leans supportive.",
    'storm-order': "Channel weather and tempest. Trained in [[acrobatics|Acrobatics]]. Order Spell is Tempest Surge — a single-target elemental damage strike. You gain the Storm Born feat for ignoring weather-based [[perception|Perception]] penalties. Anathema is polluting the air or allowing climate harm to go unpunished. Mechanically the most direct-damage Druid order. Pairs with parties needing reliable single-target elemental damage from their primal caster. Best for players who want the 'weather mage' fantasy — wind, rain, lightning at your command. Skip if you prefer healing/support or shapeshifting roles — Storm leans offensive.",
    'untamed-order': "The shapeshifter. Trained in [[intimidation|Intimidation]]. Order Spell is Untamed Shift — your signature transformation ability, letting you become various creatures. Druid Feat is Untamed Form, expanding what shapes you can take. Anathema is becoming domesticated by civilization (you can still live in cities but never depend on them). The wild, [[primal]] Druid — combat through transformation. Pairs with parties that benefit from a shapeshifting scout/striker. Best for players who want the 'werewolf without the curse' fantasy — wild forms as your primary tool. Skip if you don't want to manage form-specific stat blocks during combat — Untamed adds real complexity per shift.",
    'flame-order': "Channel the elemental plane of Fire. Your Order grants fire-themed [[focus-spell|focus spells]] and elemental resistance to fire that scales with [[level]]. Anathema is allowing fire to be extinguished disrespectfully or to be used wastefully. Pairs with offensive caster builds — Flame leans into direct damage. Best for players who want the 'fire wizard but primal' fantasy — explosive elemental power. Skip if your campaign features many fire-resistant enemies — Flame's signature damage type runs into resistances often.",
    'stone-order': "Channel the elemental plane of Earth. Your Order grants earth-themed [[focus-spell|focus spells]] and bonuses to defenses while in contact with the ground or stone surfaces. Anathema is allowing land to be despoiled or stone monuments to be destroyed. Pairs with tanky builds that emphasize positioning and immovability. Best for players who want the 'mountain made flesh' fantasy — slow, sturdy, devastating when committed. Skip if you want fast-moving combat — Stone leans into being unmoved rather than dynamic.",
    'wave-order': "Channel the elemental plane of Water. Your Order grants water-themed [[focus-spell|focus spells]] and bonuses while in or near water. Anathema is polluting water sources. Pairs with campaigns that involve coastal, riverine, or oceanic environments. Best for players who want the 'tidal force' fantasy — flowing, reshaping, occasionally crushing. Skip if your campaign rarely features water terrain — Wave's environmental bonuses are real but situational.",
  },

  // ─── ORACLE MYSTERIES (picker not yet wired) ───────────────────────────
  oracle: {
    ancestors: "Channel the wisdom and burden of those who came before. Your Mystery binds you to ancestral spirits — they protect, advise, and sometimes meddle. Trained in [[occultism|Occultism]]. Curse manifests as ancestral spirits temporarily possessing you, making you clumsy as your movement is interfered with. Revelation spells channel ancestral knowledge and protective magic. Pairs with builds emphasizing knowledge skills and supportive magic. Best for players who want the 'medium / haunted scholar' fantasy — bearing the legacy of the dead. Skip if you don't want curse-mechanic resource management — Ancestors' curse engages mid-combat regularly.",
    battle: "Channel the spirit of warfare itself. Your Mystery grants martial proficiencies unusual for a caster — trained in medium and heavy armor, plus a weapon group. Trained in [[athletics|Athletics]]. Curse manifests through your physical body — wounds heal slower, scars accumulate. Revelation spells enhance combat prowess. Pairs with frontline-caster builds. Best for players who want the 'crusader oracle' fantasy — divine magic AND martial combat presence. Skip if you want a typical squishy caster — Battle Oracle deliberately blurs the martial/caster line.",
    bones: "Channel death and undeath. Your Mystery imparts understanding of mortality's macabre side. Trained in [[medicine|Medicine]]. Curse manifests as your body slowly decaying — bloodless pallor, deathly cold skin, faint smell of grave. Revelation spells span void damage, undead manipulation, and soul magic. Pairs with parties facing undead opposition or campaigns about death's mysteries. Best for players who want the 'grim necromantic oracle' fantasy. Skip if you want to play a brightly heroic character — Bones leans dark by design.",
    cosmos: "Channel celestial bodies and the void between stars. Your Mystery grants resistance to physical damage scaled to your [[level]] — your body is partly astronomical. Trained in [[nature|Nature]]. Curse manifests as your body drifting lighter and less substantial. Revelation spells span gravity manipulation, stellar light, and cosmic awareness. Pairs with builds that want defensive bulk plus thematic magic. Best for players who want the 'star-touched mystic' fantasy. Skip if you don't want curse-as-physical-change — Cosmos transforms your body visibly.",
    flames: "Channel sacred and destructive fire. Your Mystery grants fire-themed [[focus-spell|focus spells]] and bonuses to fire-based magic. Trained in [[acrobatics|Acrobatics]]. Curse manifests as your body running hotter — sweating, dry mouth, eventually low-level persistent fire damage in your most cursed states. Revelation spells span fire damage, light, and purification. Pairs with offensive caster builds. Best for players who want the 'burning prophet' fantasy — fiery zealot energy. Skip if your campaign features fire-resistant enemies frequently — Flames' damage runs into resistances.",
    life: "Channel positive energy and healing. Your Mystery grants healing-themed [[focus-spell|focus spells]] and bonuses to vitality effects. Trained in [[medicine|Medicine]]. Curse manifests as your healing magic harming YOU in subtle ways — sympathetic injury, life force seeping out as you channel it for others. Revelation spells span healing, vitality damage to undead, and protective magic. Pairs perfectly with parties that need a dedicated healer. Best for players who want the 'martyr-medic' fantasy — sacrificing self to save others. Skip if you don't want to be the primary healer — Life Oracle's identity centers on healing.",
    lore: "Channel knowledge itself. Your Mystery grants additional spells in your repertoire — you simply KNOW more magic than other oracles. Trained in [[occultism|Occultism]] PLUS a [[lore|Lore]] skill of your choice. Curse manifests as overwhelming information — mind races with irrelevant facts, struggling to focus mid-combat. Revelation spells emphasize divination and knowledge. Pairs with [[intelligence|INT]]-secondary builds and parties that benefit from skill-monkey utility. Best for players who want the 'mystical librarian' fantasy. Skip if you want straightforward combat magic — Lore leans toward utility and information over damage.",
    tempest: "Channel storms in wind and water. Your Mystery grants perfect sight through wind, rain, and water — no [[perception|Perception]] penalties from weather. When you deal physical damage with air or water spells, you add electricity damage. Trained in [[nature|Nature]]. Curse manifests as your own personal weather — wind whips around you, rain falls only on you, worsens with mystery use. Revelation spells span lightning, wind, and water control. Pairs with builds that want signature elemental flavor. Best for players who want the 'storm caller' fantasy. Skip if you don't want a constant visual effect surrounding your character — Tempest's curse is dramatic.",
    time: "Channel the flow of past, present, and future. Your Mystery grants brief precognitive glimpses and minor time-manipulation effects. Trained in [[society|Society]]. Curse manifests as time slipping around you — sudden aging effects, lost moments, memory flickers. Revelation spells span haste, slow, and prophetic insight. Pairs with tactical builds that benefit from action-economy manipulation. Best for players who want the 'seer / time-touched mystic' fantasy. Skip if your table doesn't enjoy meta-narrative time effects — Time's flavor demands engagement with prophecy and fate.",
  },

};

export function getSubclassTip(classSlug, subclassId) {
  return SUBCLASS_TIPS[classSlug]?.[subclassId] || null;
}
