// Per-subclass new-player tips.
//
// Two-level dictionary: class slug → subclass id → tip string.
//
// Subclass IDs follow the picker's `class-details.json` short IDs where a
// picker exists (Barbarian, Rogue today). For classes whose picker has
// not been wired yet (Champion, Ranger, Swashbuckler in this batch), the
// IDs match the canonical Foundry class-feature slugs from
// audits/pf2e_subclass_inventory.json — the tips sit dormant until a
// picker for that class is added, at which point the IDs line up.
//
// Tip strings may contain inline [[slug]] markers parsed by AnnotatedText
// against the foundational glossary.

export const SUBCLASS_TIPS = {
  // ─── BARBARIAN INSTINCTS ────────────────────────────────────────────────
  barbarian: {
    animal: "Channel a wild predator. Pick an animal (ape, bear, deer, frog, shark, snake, spider, wolf) — your Rage replaces your weapon attacks with that animal's unarmed strike. Bears get claws, snakes get fangs and a constrict, spiders get web — each animal grants different mechanical options and a thematic feel. While raging you can't use weapons; the animal IS your weapon. Pairs well with [[ancestry-feat|ancestry feats]] that lean into natural attacks. Anathema is disrespecting your chosen animal — flavor with mechanical teeth. Best for players who want a transformation fantasy in combat. Skip if you prefer wielding a specific weapon throughout.",
    dragon: "Channel draconic ancestry. Pick a dragon type — your Rage damage shifts to that dragon's elemental damage type (fire for red, cold for white, electricity for blue, etc.). At higher levels you can spend a [[focus-pool|focus]] action for a breath-weapon-like cone or line attack. Anathema is allowing disrespect to your dragon type. Pairs well with characters built around a specific elemental theme. Best for players who want martial damage with elemental flavor and the occasional area-of-effect option. Skip if you want pure physical damage without elemental complications — Dragon's damage-type shift can hurt you against resistant enemies.",
    elemental: "Bond with one of the elemental planes (air, earth, fire, metal, water, wood). Your Rage damage takes on that element's damage type, and you gain elemental resistances at higher levels. Similar to Dragon Instinct mechanically but tied to elemental planes and creatures rather than dragons. Anathema is disrespecting your chosen element's elementals. Best for players who want elemental flavor without committing to a specific dragon mythology. Skip if you want martial damage that always lands — elemental damage types can be resisted.",
    fury: "Pure unfiltered rage with no source mythology — your fury wells from your own heart. NO anathema, NO instinct ability — you trade those for an EXTRA [[class-feat|class feat]] at level 1 AND increased Rage damage (jumps from 2 to 6, escalating to 12 at higher levels). The simplest instinct mechanically; the most damaging numerically. Pairs with literally any campaign — no flavor restrictions, no anathema to watch. Best for players who want straightforward 'big damage, simple rules' Barbarian play. Skip only if you want the flavor of a specific instinct's theme.",
    giant: "Channel the raw power and size of giants. The signature feature: you can wield weapons sized for a [[size|Large]] creature even if you're Small or Medium, dealing massive damage at the cost of clumsiness (–2 to attack rolls while using oversized weapons during Rage). Anathema is letting an insult to giants slide. The trade-off is brutal: harder to hit, but the damage when you DO hit is staggering. Pairs with reach weapons and high-crit builds. Best for players who want maximum damage swings — the 'either crit or whiff' style. Skip if you want consistent hits — Giant's penalty is a real cost.",
    spirit: "Channel ancestral or spectral powers. Your Rage damage shifts to negative or void damage — perfect against undead and living creatures alike (though some undead resist negative). Higher levels grant access to spirit-themed [[focus-spell|focus spells]] and resistances to negative effects. Anathema is disrespecting corpses or spirits. Best for undead-heavy campaigns or for players who want martial flavor with a haunted backstory. Skip if your party already has anti-undead specialists — Spirit Instinct's edge case is exactly what other classes already cover.",
    superstition: "Anti-magic Barbarian. While raging you gain +2 to [[saving-throw|saves]] against magic AND deal extra Rage damage to anyone you've witnessed casting a [[spell]] recently. The anathema is steep: you cannot learn or cast spells, or use spell-activated items — accepting magic willingly even from allies makes you Frightened. Best for campaigns with caster-heavy enemies and parties that don't rely on you for magical buff acceptance. Skip if your party uses heal-via-magic frequently — Superstition's anti-magic stance creates real friction with party cleric/druid support.",
  },

  // ─── CHAMPION CAUSES (picker not yet wired — IDs match Foundry slugs) ───
  champion: {
    justice: "The shining knight. Tenets of Good: never act against innocents, defend the helpless, respect lawful authority unless it conflicts with deeper good. Your reactive ability is Retributive Strike — when an ally near you is hit, you deal damage to the attacker. Excellent for protecting squishy allies; the threat of your reaction makes enemies think twice about ignoring you. Pairs well with parties that have casters or archers behind you. Best for players who want the classic 'shining defender' fantasy. Skip if you want moral flexibility — Justice's tenets are strict and consistent.",
    liberation: "The defender of freedom. Tenets of Good combined with anti-tyranny — you must aid those whose freedom is threatened, can't enslave or oppress. Your reactive ability is Liberating Step — when an ally near you is grabbed, restrained, or otherwise restricted, you can free them as a [[reaction]]. Excellent against monsters with grapples, charms, or holds. Pairs with parties facing enchanter or beholder-style opposition. Best for players who want anti-tyranny themes and a less rigid version of the holy knight fantasy. Skip if your party doesn't typically face grappling/binding opposition — the reaction's specific trigger is real.",
    redemption: "The merciful warrior. Tenets of Good plus an obligation to offer enemies a chance to relent before killing them. Your reactive ability is Glimpse of Redemption — when an ally is hit, the attacker chooses: stop attacking the ally (and become enfeebled briefly) or take resistance-reduced damage themselves. Excellent at de-escalating fights and protecting allies through choice manipulation. Pairs with parties that benefit from narrative-driven combat over kill-everything tactics. Best for players who want the 'show mercy where possible' fantasy. Skip if your campaign features purely evil enemies who'll never accept mercy — Redemption's option becomes redundant.",
    iniquity: "The fallen knight. Tenets of Evil mirror of Justice — you embrace cruelty, manipulate the weak, scorn mercy. Your reactive ability flavors as vengeful spite — when allies are wronged, the offender suffers. Anathema is allowing kindness to define your behavior. Pairs with morally complex campaigns or evil-aligned parties (rare but possible). Best for players who want the dark mirror of the holy knight fantasy. Skip if your campaign or table doesn't support evil-aligned PCs — Iniquity is fundamentally a villainous archetype.",
    obedience: "The dominating ruler. Tenets of Evil plus an obsession with control — you must impose order through fear, dominate the weak, deny freedom to those beneath you. Your reactive ability is Destructive Vengeance — when allies are crossed, the offender takes additional damage as punishment. Anathema is allowing disobedience to go unpunished. Best for villain campaigns or 'controlled chaos' party dynamics. Skip if your party isn't evil — Obedience's control theme grates against good-aligned dynamics.",
    desecration: "The corruptor. Tenets of Evil plus a drive to defile sacred things — holy ground, holy creatures, sacred objects. Your reactive ability lets you defile a hostile aura around you, draining ally power. Anathema is showing reverence for things others find holy. Best for evil campaigns where corruption is the goal. Skip if your party is good-aligned — Desecration's identity centers on actively undermining good-aligned allies' values.",
  },

  // ─── RANGER HUNTER'S EDGES (picker not yet wired) ──────────────────────
  ranger: {
    flurry: "Multi-attack specialist. Your Hunt Prey grants reduced [[multiple-attack-penalty|MAP]] against your designated target — −3/−6 instead of the standard −5/−10. The math turns triple-Striking from 'usually a bad idea' to 'genuinely viable'. Pairs with two-weapon fighting, agile weapons, and any build that wants to swing multiple times per turn against the same enemy. Best for players who want to maximize attack volume — bows, dual blades, or grappler builds. Skip if you prefer single big strikes — Precision is the alternative for that style.",
    outwit: "Tactical and informational specialist. Your Hunt Prey grants [[skill]] bonuses to [[deception|Deception]], [[intimidation|Intimidation]], [[stealth|Stealth]], and Recall Knowledge checks against the target, plus a bonus to [[armor-class|AC]] specifically against the target's attacks. Less direct damage than Flurry or Precision; more about tactical advantage and survivability. Best for players who want their Ranger to be the party's tracker-and-tactician. Pairs well with [[intelligence|INT]]-heavy builds and skill-focused playstyles. Skip if you want pure combat optimization — Outwit's bonuses are diffuse rather than concentrated.",
    precision: "Big-hit specialist. Your first hit against your Hunted Prey each round deals significant bonus damage — 1d8 at low levels, scaling up. The damage is added to a single hit, making each round feature one impactful strike. Pairs perfectly with high-crit builds and weapons with strong base damage (bows, crossbows, heavy melee). Best for players who want the 'ranger as sniper' or 'ranger as duelist' fantasy. Skip if you want to attack multiple times per round consistently — Flurry handles that better.",
  },

  // ─── ROGUE RACKETS ──────────────────────────────────────────────────────
  rogue: {
    'eldritch-trickster': "The magic-using sneak. Key ability options include [[charisma|CHA]] or another spellcasting stat alongside [[dexterity|DEX]]. Your racket grants access to a small selection of [[spell|spells]] from one tradition, scaling up as you level. Effectively makes you a magic-dabbling Rogue without going full multiclass. Best for players who want the 'arcane assassin' or 'shadow magic thief' fantasy — magical utility on top of Rogue's signature [[skill]] mastery. Skip if you don't want spell management on top of Rogue's positioning game — Eldritch Trickster adds real complexity.",
    mastermind: "The brain-over-brawn rogue. Key ability is [[intelligence|INT]] — your Sneak Attack triggers off making Recall Knowledge against an enemy AND succeeding, not off positioning alone. Trades the flanking-and-feinting playstyle for a tactical 'study before strike' approach. Pairs well with [[society|Society]], [[arcana|Arcana]], and other knowledge skills. Best for players who want a cerebral Rogue — Sherlock Holmes meets dagger work. Skip if you want straightforward Sneak Attack triggers — Mastermind's setup involves more reading the room than positioning.",
    ruffian: "The brawler thief. Key ability is [[strength|STR]] — your racket grants Sneak Attack with medium armor and martial weapons (instead of the typical light armor + finesse weapons). Heavier hits, more durability, but reduced [[stealth|Stealth]] effectiveness due to armor noise. Pairs well with mauls, picks, and heavy weapons. Best for players who want the 'street thug' fantasy — Rogues who don't sneak in shadows but punch their way into ambushes. Skip if you want delicate finesse weapon play — Ruffian leans STR-loud.",
    scoundrel: "The trickster face. Key ability is [[charisma|CHA]] — Sneak Attack triggers off successful Feint actions, which use [[deception|Deception]] to make enemies flat-footed against you. Plays as a fast-talking street trickster who weaponizes social interaction even mid-combat. Pairs with high-CHA builds and any party that needs a social face. Best for players who want their Rogue to be the party diplomat-by-day, ambusher-by-night. Skip if you don't want to engage with social mechanics constantly — Scoundrel's identity is built around them.",
    thief: "The classic finesse thief. Key ability is [[dexterity|DEX]] — your racket lets you add DEX modifier to damage rolls with finesse weapons (normally STR adds to damage even on finesse weapons). DEX-based damage means you can build a fully agile Rogue without splitting stats. The default and most-played Rogue racket. Best for players who want the iconic 'small fast knife-user' fantasy — Rogue as nimble striker. Skip if you have a strong concept that points elsewhere; Thief is the safe default but other rackets offer more specific identity.",
  },

  // ─── SWASHBUCKLER STYLES (picker not yet wired) ────────────────────────
  swashbuckler: {
    battledancer: "Performance-fueled panache. You gain Panache through [[performance|Performance]] checks during combat — Tumble Through, Demoralize via display, or specific style actions. Trained in Performance automatically. Best for players who want the 'flashy showman' fantasy — combat as art form. Pairs with [[charisma|CHA]] builds where Performance is your social and combat skill simultaneously. Skip if you want a tactical, less theatrical Swashbuckler.",
    braggart: "Intimidation-fueled panache. You gain Panache through successful [[intimidation|Intimidation]] checks — primarily Demoralize. Trained in Intimidation automatically. Combat becomes a back-and-forth of taunts and threats backed by steel. Pairs well with high-CHA frontline builds. Best for players who want the 'cocky duelist' fantasy — talk loud, hit hard. Skip if Intimidation doesn't fit your character — Braggart leans into being a confident jerk in combat.",
    fencer: "Acrobatic panache. You gain Panache through successful [[acrobatics|Acrobatics]] Tumble Through actions — slip past enemies, gain Panache, then strike. Trained in Acrobatics automatically. The most physically dynamic style, emphasizing movement and positioning. Pairs with high-DEX builds and reach-conscious play. Best for players who want the 'duelist as dancer' fantasy — combat through grace. Skip if you don't want to constantly move around the battlefield — Fencer's style demands movement.",
    gymnast: "Athletics-fueled panache. You gain Panache through successful [[athletics|Athletics]] actions during combat — Grapple, Shove, Trip, Disarm. Trained in Athletics automatically. Combines Swashbuckler flair with grappler-style control mechanics. Pairs with [[strength|STR]] and [[dexterity|DEX]] dual focus. Best for players who want 'duelist meets wrestler' — flashy combat moves backed by physical control. Skip if you want to stay at weapon range — Gymnast pushes you into close-quarters combat.",
    wit: "Diplomacy-fueled panache. You gain Panache through successful [[diplomacy|Diplomacy]] actions during combat — primarily the Bon Mot skill feat (which acts as a verbal Demoralize). Trained in Diplomacy automatically. The most social style, emphasizing words over actions. Pairs with [[charisma|CHA]] builds where Diplomacy serves both social and combat needs. Best for players who want the 'duelist as silver-tongued charmer' fantasy. Skip if you don't want to engage in verbal jousting during fights — Wit's actions are talky by design.",
    rascal: "Deception-fueled panache. You gain Panache through successful [[deception|Deception]] Feints in combat. Trained in Deception automatically. The deceiver-duelist who confuses enemies into vulnerable positions. Pairs with builds that want to weave illusion and trickery into melee. Best for players who want the 'rogue meets swashbuckler' fantasy — deception applied with style. Skip if you want straightforward combat — Rascal's style requires setup feints every round.",
  },
};

export function getSubclassTip(classSlug, subclassId) {
  return SUBCLASS_TIPS[classSlug]?.[subclassId] || null;
}
