// Druidic symbol catalog. The 30 SVGs are code-generated by
// scripts/generateDruidicSymbols.js and uploaded to Supabase Storage
// under campaign-assets/dnd5e/languages/Druidic. They're authored
// with stroke="currentColor" + fill="none" so CSS-mask tinting works
// from any colour the GM picks per world-lore entry.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const DRUIDIC_BASE = `${SUPABASE_URL}/storage/v1/object/public/campaign-assets/dnd5e/languages/Druidic`;

export const DRUIDIC_SYMBOLS = [
  // Navigation & Territory
  { id: 'safe-path',             name: 'Safe Path',             category: 'Navigation', src: `${DRUIDIC_BASE}/safe-path.svg` },
  { id: 'danger-path',           name: 'Dangerous Path',        category: 'Navigation', src: `${DRUIDIC_BASE}/danger-path.svg` },
  { id: 'water-source',          name: 'Water Source',          category: 'Navigation', src: `${DRUIDIC_BASE}/water-source.svg` },
  { id: 'shelter-ahead',         name: 'Shelter Ahead',         category: 'Navigation', src: `${DRUIDIC_BASE}/shelter-ahead.svg` },
  { id: 'sacred-ground',         name: 'Sacred Ground',         category: 'Navigation', src: `${DRUIDIC_BASE}/sacred-ground.svg` },
  { id: 'corrupted-land',        name: 'Corrupted Land',        category: 'Navigation', src: `${DRUIDIC_BASE}/corrupted-land.svg` },
  { id: 'fey-crossing',          name: 'Fey Crossing',          category: 'Navigation', src: `${DRUIDIC_BASE}/fey-crossing.svg` },
  { id: 'ley-line',              name: 'Ley Line',              category: 'Navigation', src: `${DRUIDIC_BASE}/ley-line.svg` },
  { id: 'migration-route',       name: 'Migration Route',       category: 'Navigation', src: `${DRUIDIC_BASE}/migration-route.svg` },
  { id: 'territorial-boundary',  name: 'Territorial Boundary',  category: 'Navigation', src: `${DRUIDIC_BASE}/territorial-boundary.svg` },

  // Warnings & Information
  { id: 'predator-territory',    name: 'Predator Territory',    category: 'Warnings', src: `${DRUIDIC_BASE}/predator-territory.svg` },
  { id: 'poisonous-plants',      name: 'Poisonous Plants',      category: 'Warnings', src: `${DRUIDIC_BASE}/poisonous-plants.svg` },
  { id: 'healing-herbs',         name: 'Healing Herbs',         category: 'Warnings', src: `${DRUIDIC_BASE}/healing-herbs.svg` },
  { id: 'rare-ingredient',       name: 'Rare Ingredient',       category: 'Warnings', src: `${DRUIDIC_BASE}/rare-ingredient.svg` },
  { id: 'storm-coming',          name: 'Storm Coming',          category: 'Warnings', src: `${DRUIDIC_BASE}/storm-coming.svg` },
  { id: 'seasonal-danger',       name: 'Seasonal Danger',       category: 'Warnings', src: `${DRUIDIC_BASE}/seasonal-danger.svg` },
  { id: 'undead-presence',       name: 'Undead Presence',       category: 'Warnings', src: `${DRUIDIC_BASE}/undead-presence.svg` },
  { id: 'aberration-taint',      name: 'Aberration Taint',      category: 'Warnings', src: `${DRUIDIC_BASE}/aberration-taint.svg` },
  { id: 'wildfire-risk',         name: 'Wildfire Risk',         category: 'Warnings', src: `${DRUIDIC_BASE}/wildfire-risk.svg` },
  { id: 'flood-zone',            name: 'Flood Zone',            category: 'Warnings', src: `${DRUIDIC_BASE}/flood-zone.svg` },

  // Social & Community
  { id: 'druid-circle-nearby',   name: 'Druid Circle Nearby',   category: 'Community', src: `${DRUIDIC_BASE}/druid-circle-nearby.svg` },
  { id: 'grove-meeting',         name: 'Grove Meeting',         category: 'Community', src: `${DRUIDIC_BASE}/grove-meeting.svg` },
  { id: 'friendly-settlement',   name: 'Friendly Settlement',   category: 'Community', src: `${DRUIDIC_BASE}/friendly-settlement.svg` },
  { id: 'hostile-settlement',    name: 'Hostile Settlement',    category: 'Community', src: `${DRUIDIC_BASE}/hostile-settlement.svg` },
  { id: 'logging-threat',        name: 'Logging Threat',        category: 'Community', src: `${DRUIDIC_BASE}/logging-threat.svg` },
  { id: 'mining-threat',         name: 'Mining Threat',         category: 'Community', src: `${DRUIDIC_BASE}/mining-threat.svg` },
  { id: 'ally-creature',         name: 'Ally Creature',         category: 'Community', src: `${DRUIDIC_BASE}/ally-creature.svg` },
  { id: 'beast-companion',       name: 'Beast Companion',       category: 'Community', src: `${DRUIDIC_BASE}/beast-companion.svg` },
  { id: 'ritual-site',           name: 'Ritual Site',           category: 'Community', src: `${DRUIDIC_BASE}/ritual-site.svg` },
  { id: 'ancient-tree',          name: 'Ancient Tree',          category: 'Community', src: `${DRUIDIC_BASE}/ancient-tree.svg` },
];

export const DRUIDIC_CATEGORIES = [...new Set(DRUIDIC_SYMBOLS.map((s) => s.category))];

export const DRUIDIC_COLOR_PRESETS = [
  { id: 'emerald', value: '#10b981' },
  { id: 'forest',  value: '#166534' },
  { id: 'moss',    value: '#65a30d' },
  { id: 'bark',    value: '#78350f' },
  { id: 'dusk',    value: '#9333ea' },
  { id: 'sky',     value: '#0ea5e9' },
  { id: 'amber',   value: '#d97706' },
  { id: 'white',   value: '#f8fafc' },
];

export const DRUIDIC_DEFAULT_COLOR = '#10b981';
